@startuml
skinparam Shadowing false

actor "User" as user
entity "Simple\nFacts" as app
entity "Tahoe\n'Client' " as tahoe
collections "Tahoe\nStorage0" as disk

group Retrieve
activate app
user --> app : Request content
app -> tahoe : HTTP Get... URI
    activate tahoe
    tahoe -> tahoe : lookup URI
    tahoe ->  disk : request the shares
    tahoe <--  disk : return the shares
    tahoe -> tahoe : decrypt content
    tahoe -> app : return content
    app -> user : display content
    deactivate tahoe
deactivate app
end
@enduml