@startuml
skinparam Shadowing false

actor "User" as user
entity "Simple\nFacts" as app
entity "Tahoe\n'Client' " as tahoe
Collections "Tahoe\nStorage0" as disk

group Uploads
activate app
user --> app : "Submits some content"
    activate tahoe
    app -> tahoe : HTTP Put...
    tahoe -> tahoe : create reference id
    tahoe -> tahoe : encrypt & fragment
    tahoe ->  disk : send fragments in "shares"
    tahoe -> app : return reference id
    deactivate tahoe
app -> app : store reference id
app --> user : "Content OK"
deactivate app

end
@enduml